name: 'the_tuva_project_demo'
version: '0.1.5'
config-version: 2

profile: default

vars:

  claims_enabled: true

  ## CMS HCC data mart vars
  # Setting the payment year to year needed for the demo data
  cms_hcc_payment_year: 2019

  ## Quality Measure data mart vars
  # Setting the reporting period to date needed for demo data
  quality_measures_period_end: "2018-12-31"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  the_tuva_project_demo:
    eligibility:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/tuva_synthetic_data','eligibility.csv',headers=true) }}"
    medical_claim:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/tuva_synthetic_data','medical_claim.csv',headers=true) }}"
    pharmacy_claim:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/tuva_synthetic_data','pharmacy_claim.csv',headers=true) }}"
