name: 'tuva_claims_demo'
version: '0.1.3'
config-version: 2

profile: tuva_claims_demo     # Configuration required (your profile to connect dbt to your data warehouse)

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tuva_claims_demo:
    +materialized: view
    +schema: tuva_claims_demo
    +tags: tuva_claims_demo
