default: # Replace with your project name
  target: ci
  outputs:
    ci:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: 5439
      dbname: "{{ env_var('REDSHIFT_DB') }}"
      schema: public
      threads: 4
      keepalives_idle: 240
      connect_timeout: 10