name: weekly_dbt_v1.6.3_snowflake_dev_build_full_refresh

on:
  workflow_dispatch:
  schedule:
    # This job will run at midnight on Fridays
    - cron: '0 0 * * SAT'

env:
  DBT_SNOWFLAKE_DEV_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_DEV_ACCOUNT }}
  DBT_SNOWFLAKE_DEV_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DEV_DATABASE }}
  DBT_SNOWFLAKE_DEV_CI_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_DEV_CI_PASSWORD }}
  DBT_SNOWFLAKE_DEV_CI_ROLE: ${{ secrets.DBT_SNOWFLAKE_DEV_CI_ROLE }}
  DBT_SNOWFLAKE_DEV_CI_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_DEV_CI_SCHEMA }}
  DBT_SNOWFLAKE_DEV_CI_USER: ${{ secrets.DBT_SNOWFLAKE_DEV_CI_USER }}
  DBT_SNOWFLAKE_DEV_CI_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_DEV_CI_WAREHOUSE }}

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt deps --profiles-dir ./integration_tests/profiles/snowflake_dev --target dev"

      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt debug --profiles-dir ./integration_tests/profiles/snowflake_dev --target dev"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt build --full-refresh --profiles-dir ./integration_tests/profiles/snowflake_dev --target dev"

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash
