name: weekly_dbt_v1.4.6_snowflake_prod_build_full_refresh

on:
  workflow_dispatch:
  schedule:
    # This job will run at midnight on Fridays
    - cron: '0 0 * * FRI'

env:
  DBT_SNOWFLAKE_PROD_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_PROD_ACCOUNT }}
  DBT_SNOWFLAKE_PROD_USER: ${{ secrets.DBT_SNOWFLAKE_PROD_USER }}
  DBT_SNOWFLAKE_PROD_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PROD_PASSWORD }}
  DBT_SNOWFLAKE_PROD_DATABASE: ${{ secrets.DBT_SNOWFLAKE_PROD_DATABASE }}
  DBT_SNOWFLAKE_PROD_ROLE: ${{ secrets.DBT_SNOWFLAKE_PROD_ROLE }}
  DBT_SNOWFLAKE_PROD_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_PROD_SCHEMA }}
  DBT_SNOWFLAKE_PROD_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_PROD_WAREHOUSE }}

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt deps --profiles-dir ./integration_tests/profiles/snowflake_prod"

      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt debug --profiles-dir ./integration_tests/profiles/snowflake_prod"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt build --full-refresh --profiles-dir ./integration_tests/profiles/snowflake_prod"

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash
